### ISSUE TITLE
Question about pagination

### ISSUE THREAD

**Issue by sindrehauglum** [documaster/documaster-api#28]
This is a question, please let me know if this is not an appropriate way to ask questions.

The  `QueryResponse `has the flag `hasMore`. How can I utilize this to achieve pagination when the `NoarkClient.query` method do not take parameters for  `pageStart`. 

Is this flag intended for the caller to increase the `limit` if the flag is raised?

**Comment by dkumanov** [comment]
Hey Sindre,

You can ask questions about the C# client in the [Noark 5 web-services repository](https://github.com/documaster/noark5-web-services).

To answer your concrete question, we do support setting the page start and the page size parameters. You can set the page start using the `SetOffset()` method. The page size is always set as a constructor parameter. A concrete code example if you want to fetch a page of 5 Case Files with an offset of 10 would go like that:

`new NoarkClient(<server_address>).Query<Saksmappe>(5).SetOffset(10);`

**Comment by sindrehauglum** [comment]
Thank you! This was very helpful.
